// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDd7_3HYz5Lq8du31URVeTMWO0CUxJFng',
    appId: '1:218324312204:web:49a5779232bc9a418b9ba9',
    messagingSenderId: '218324312204',
    projectId: 'wasteless-app-2034e',
    authDomain: 'wasteless-app-2034e.firebaseapp.com',
    storageBucket: 'wasteless-app-2034e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4_rkaL-fWtP0x-BjsbR_9hg4dKu0rfYI',
    appId: '1:218324312204:android:b79124c3c7efe1788b9ba9',
    messagingSenderId: '218324312204',
    projectId: 'wasteless-app-2034e',
    storageBucket: 'wasteless-app-2034e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNTnJpcemAxyBnM56jc8VxsR2f7odPLsI',
    appId: '1:218324312204:ios:0fb424c76c2404468b9ba9',
    messagingSenderId: '218324312204',
    projectId: 'wasteless-app-2034e',
    storageBucket: 'wasteless-app-2034e.firebasestorage.app',
    iosBundleId: 'com.example.wastelessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNTnJpcemAxyBnM56jc8VxsR2f7odPLsI',
    appId: '1:218324312204:ios:0fb424c76c2404468b9ba9',
    messagingSenderId: '218324312204',
    projectId: 'wasteless-app-2034e',
    storageBucket: 'wasteless-app-2034e.firebasestorage.app',
    iosBundleId: 'com.example.wastelessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDd7_3HYz5Lq8du31URVeTMWO0CUxJFng',
    appId: '1:218324312204:web:c402392c60878ea08b9ba9',
    messagingSenderId: '218324312204',
    projectId: 'wasteless-app-2034e',
    authDomain: 'wasteless-app-2034e.firebaseapp.com',
    storageBucket: 'wasteless-app-2034e.firebasestorage.app',
  );
}
